sudo: required

language: node_js
node_js:
  - 6
services:
  - docker
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t delta62/oscar-static .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push delta62/oscar-static;
    fi
